//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZagAPIServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZagAPIServer.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml SBAcctInq.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_Zag_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;AcctInq&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;BRK&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt;/EntityId&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccINQ {
            get {
                return ResourceManager.GetString("AccINQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.finacle.com/fixml AcctInq.xsd&quot;&gt;
        ///	&lt;Header&gt;
        ///		&lt;ResponseHeader&gt;
        ///			&lt;RequestMessageKey&gt;
        ///				&lt;RequestUUID&gt;Req_15136323420714131&lt;/RequestUUID&gt;
        ///				&lt;ServiceRequestId&gt;AcctInq&lt;/ServiceRequestId&gt;
        ///				&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///				&lt;ChannelId&gt;BRK&lt;/ChannelId&gt;
        ///			&lt;/RequestMessageKey&gt;
        ///			&lt;ResponseMessageInfo&gt;
        ///				&lt;BankId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccINQRep {
            get {
                return ResourceManager.GetString("AccINQRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml AcctLienAdd.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_Zag_Trans_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;AcctLienAdd&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddLIEN {
            get {
                return ResourceManager.GetString("AddLIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml AcctLienMod.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;AcctLienMod&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt;/EntityId&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddNextLien {
            get {
                return ResourceManager.GetString("AddNextLien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml BalInq.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_Zag_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;BalInq&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt;/EntityId&gt;
        ///&lt;Ent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BalInc {
            get {
                return ResourceManager.GetString("BalInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml AcctLienMod.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_Zag_Trans_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;AcctLienMod&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DelLIEN {
            get {
                return ResourceManager.GetString("DelLIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml AcctLienInq.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;AcctLienInq&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/TimeZone&gt;
        ///&lt;EntityId&gt;&lt;/EntityId&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllLien {
            get {
                return ResourceManager.GetString("GetAllLien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xsi:schemaLocation=&quot;http://www.finacle.com/fixml getLastNTransactions.xsd&quot; xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Header&gt;
        ///&lt;RequestHeader&gt;
        ///&lt;MessageKey&gt;
        ///&lt;RequestUUID&gt;Req_Zag_Trans_X&lt;/RequestUUID&gt;
        ///&lt;ServiceRequestId&gt;getLastNTransactions&lt;/ServiceRequestId&gt;
        ///&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///&lt;/MessageKey&gt;
        ///&lt;RequestMessageInfo&gt;
        ///&lt;BankId&gt;01&lt;/BankId&gt;
        ///&lt;TimeZone&gt;&lt;/Time [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastTransactions {
            get {
                return ResourceManager.GetString("LastTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FIXML xmlns=&quot;http://www.finacle.com/fixml&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; schemaLocation=&quot;http://www.finacle.com/fixml executeFinacleScript.xsd&quot;&gt;
        ///   &lt;Header&gt;
        ///	  &lt;RequestHeader&gt;
        ///		 &lt;MessageKey&gt;
        ///			&lt;RequestUUID&gt;Req_Zag_ADD_Trans_X&lt;/RequestUUID&gt;
        ///			&lt;ServiceRequestId&gt;XferTrnAdd&lt;/ServiceRequestId&gt;
        ///			&lt;ServiceRequestVersion&gt;10.3&lt;/ServiceRequestVersion&gt;
        ///			&lt;ChannelId&gt;SMS&lt;/ChannelId&gt;
        ///		 &lt;/MessageKey&gt;
        ///		 &lt;RequestMessageInfo&gt;
        ///			&lt;BankId&gt;01&lt;/Ban [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendTransActions {
            get {
                return ResourceManager.GetString("SendTransActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PartTrnRec&gt;
        ///				  &lt;AcctId&gt;
        ///					 &lt;AcctId&gt;ZAGACCID&lt;/AcctId&gt;
        ///					 &lt;AcctCurr&gt;ZAG1CURRENCY&lt;/AcctCurr&gt;
        ///				  &lt;/AcctId&gt;
        ///				  &lt;CreditDebitFlg&gt;ZAGFLAG&lt;/CreditDebitFlg&gt;
        ///				  &lt;TrnAmt&gt;
        ///					 &lt;amountValue&gt;ZAGAMOUNT&lt;/amountValue&gt;
        ///					 &lt;currencyCode&gt;ZAGCURRENCY&lt;/currencyCode&gt;
        ///				  &lt;/TrnAmt&gt;
        ///				  &lt;TrnParticulars&gt;ZAGTRNPRT&lt;/TrnParticulars&gt;
        ///				  &lt;ValueDt&gt;ZAGDATE&lt;/ValueDt&gt;
        ///				  &lt;Rate&gt;ZAGRATE&lt;/Rate&gt;
        ///				  &lt;RateCode&gt;ZAG1RATECODE&lt;/RateCode&gt;
        ///				  &lt;SERIALNUM&gt;ZAGSERIAL&lt;/SERIALNUM&gt;
        ///			   &lt;/PartTrnRec&gt;.
        /// </summary>
        internal static string TransLeg {
            get {
                return ResourceManager.GetString("TransLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PARTTRAN isMultiRec=&quot;Y&quot;&gt;
        ///			   &lt;SERIALNUM&gt;ZAGSERIAL&lt;/SERIALNUM&gt;
        ///	  &lt;TranParticularCode&gt;ZAGPURPOSCODE&lt;/TranParticularCode&gt;
        ///			   &lt;TranParticulars2&gt;ZAGEMP&lt;/TranParticulars2&gt;
        ///			   &lt;RefNum&gt;ZAGID&lt;/RefNum&gt;
        ///&lt;DiaryNum/&gt;
        ///&lt;TODAllowed&gt;N&lt;/TODAllowed&gt;
        ///			&lt;/PARTTRAN&gt;.
        /// </summary>
        internal static string TransTail {
            get {
                return ResourceManager.GetString("TransTail", resourceCulture);
            }
        }
    }
}
