// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Linq;
using System.Drawing;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Data;
using System.Xml.Linq;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using System.Threading;
using ZagAPIServer;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ZagAPIServer
{
	namespace My  {
		
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0"), 
		global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]sealed public 
		partial class Settings : global::System.Configuration.ApplicationSettingsBase
		{
			
			private static Settings defaultInstance; // VBConversions Note: Initial value cannot be assigned here since it is non-static.  Assignment has been moved to the class constructors.
			
#region My.Settings Auto-Save Functionality
#if _MyType
			private static bool addedHandler;
			
			private static object addedHandlerLockObject = new object();
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
			{
				if ((new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).SaveMySettingsOnExit)
				{
					My.Settings.Default.Save();
				}
			}
#endif
#endregion
			
			public static Settings Default
			{
				get
				{
					
#if _MyType
					if (!addedHandler)  {
							lock(addedHandlerLockObject)  {
									if (!addedHandler)  {
											(new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).Shutdown += AutoSaveSettings;
								addedHandler = true;
							}
						}
					}
#endif
					return defaultInstance;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("99")]public int WebServerPortNumber
			{
				get
				{
					return System.Convert.ToInt32(this["WebServerPortNumber"]);
				}
				set  {
					this["WebServerPortNumber"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("False")]public bool AutoRunWebServer
			{
				get
				{
					return System.Convert.ToBoolean(this["AutoRunWebServer"]);
				}
				set  {
					this["AutoRunWebServer"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("Housing Bank IBM Websphare MQ")]public string DefWebHandler
			{
				get
				{
					return System.Convert.ToString(this["DefWebHandler"]);
				}
				set  {
					this["DefWebHandler"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("False")]public bool EnableLogging
			{
				get
				{
					return System.Convert.ToBoolean(this["EnableLogging"]);
				}
				set  {
					this["EnableLogging"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("False")]public bool HideMe
			{
				get
				{
					return System.Convert.ToBoolean(this["HideMe"]);
				}
				set  {
					this["HideMe"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("QRAAMQ1")]public string QueueManager
			{
				get
				{
					return System.Convert.ToString(this["QueueManager"]);
				}
				set  {
					this["QueueManager"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("SYSTEM.DEF.SVRCONN")]public string channelName
			{
				get
				{
					return System.Convert.ToString(this["channelName"]);
				}
				set  {
					this["channelName"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("172.31.6.78(1414)")]public string connectionName
			{
				get
				{
					return System.Convert.ToString(this["connectionName"]);
				}
				set  {
					this["connectionName"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("BRK")]public string ChannelID
			{
				get
				{
					return System.Convert.ToString(this["ChannelID"]);
				}
				set  {
					this["ChannelID"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UsePreOpenQ
			{
				get
				{
					return System.Convert.ToBoolean(this["UsePreOpenQ"]);
				}
				set  {
					this["UsePreOpenQ"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("20")]public int NumberOfPreOpenQ
			{
				get
				{
					return System.Convert.ToInt32(this["NumberOfPreOpenQ"]);
				}
				set  {
					this["NumberOfPreOpenQ"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("2011121211222")]public string PoolAccountNumber
			{
				get
				{
					return System.Convert.ToString(this["PoolAccountNumber"]);
				}
				set  {
					this["PoolAccountNumber"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("172.31.6.78")]public string HostName
			{
				get
				{
					return System.Convert.ToString(this["HostName"]);
				}
				set  {
					this["HostName"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("1414")]public string PORT
			{
				get
				{
					return System.Convert.ToString(this["PORT"]);
				}
				set  {
					this["PORT"] = value;
				}
			}
			
			[global::System.Configuration.ApplicationScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString), 
			global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVJVIRBRGT02;Initial Catalog=HB2018;Persist Security Info=True;User " + 
			"ID=zagtrader10;Password=zagtrader12")]public string ZagTraderConnectionString
			{
				get
				{
					return System.Convert.ToString(this["ZagTraderConnectionString"]);
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("True")]public bool SyncTransFromThisServer
			{
				get
				{
					return System.Convert.ToBoolean(this["SyncTransFromThisServer"]);
				}
				set  {
					this["SyncTransFromThisServer"] = value;
				}
			}
			
			[global::System.Configuration.UserScopedSettingAttribute(), 
			global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.Configuration.DefaultSettingValueAttribute("3")]public string NumberOfRetries
			{
				get
				{
					return System.Convert.ToString(this["NumberOfRetries"]);
				}
				set  {
					this["NumberOfRetries"] = value;
				}
			}
		}
	}
	
	namespace My  {
		
		[global::Microsoft.VisualBasic.HideModuleNameAttribute(), 
		global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]internal sealed class MySettingsProperty
		{
			
			[global::System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]internal static global::ZagAPIServer.My.Settings Settings
			{
				get
				{
					return global::ZagAPIServer.My.Settings.Default;
				}
			}
		}
	}
	
}
